# Generated by Django 5.0.6 on 2024-07-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
    ]
